/* ============================================
   EnhancedMagicCSS — CSS Autocomplete Data
   CSS_PROPS: array of property names
   CSS_VALUES: map of property → common values
   ============================================ */

var CSS_PROPS = [
  'align-content',
  'align-items',
  'align-self',
  'animation',
  'animation-delay',
  'animation-direction',
  'animation-duration',
  'animation-fill-mode',
  'animation-iteration-count',
  'animation-name',
  'animation-play-state',
  'animation-timing-function',
  'appearance',
  'backdrop-filter',
  'background',
  'background-attachment',
  'background-clip',
  'background-color',
  'background-image',
  'background-origin',
  'background-position',
  'background-repeat',
  'background-size',
  'border',
  'border-bottom',
  'border-bottom-color',
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'border-bottom-style',
  'border-bottom-width',
  'border-collapse',
  'border-color',
  'border-image',
  'border-left',
  'border-left-color',
  'border-left-style',
  'border-left-width',
  'border-radius',
  'border-right',
  'border-right-color',
  'border-right-style',
  'border-right-width',
  'border-style',
  'border-top',
  'border-top-color',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-top-style',
  'border-top-width',
  'border-width',
  'bottom',
  'box-shadow',
  'box-sizing',
  'clip-path',
  'color',
  'column-gap',
  'columns',
  'content',
  'cursor',
  'display',
  'filter',
  'flex',
  'flex-basis',
  'flex-direction',
  'flex-flow',
  'flex-grow',
  'flex-shrink',
  'flex-wrap',
  'float',
  'font',
  'font-family',
  'font-size',
  'font-style',
  'font-variant',
  'font-weight',
  'gap',
  'grid',
  'grid-area',
  'grid-column',
  'grid-column-end',
  'grid-column-gap',
  'grid-column-start',
  'grid-row',
  'grid-row-end',
  'grid-row-gap',
  'grid-row-start',
  'grid-template',
  'grid-template-areas',
  'grid-template-columns',
  'grid-template-rows',
  'height',
  'justify-content',
  'justify-items',
  'justify-self',
  'left',
  'letter-spacing',
  'line-height',
  'list-style',
  'list-style-position',
  'list-style-type',
  'margin',
  'margin-bottom',
  'margin-left',
  'margin-right',
  'margin-top',
  'max-height',
  'max-width',
  'min-height',
  'min-width',
  'object-fit',
  'object-position',
  'opacity',
  'order',
  'outline',
  'outline-color',
  'outline-offset',
  'outline-style',
  'outline-width',
  'overflow',
  'overflow-x',
  'overflow-y',
  'padding',
  'padding-bottom',
  'padding-left',
  'padding-right',
  'padding-top',
  'place-content',
  'place-items',
  'pointer-events',
  'position',
  'resize',
  'right',
  'rotate',
  'row-gap',
  'scale',
  'scroll-behavior',
  'text-align',
  'text-decoration',
  'text-decoration-color',
  'text-decoration-line',
  'text-decoration-style',
  'text-overflow',
  'text-shadow',
  'text-transform',
  'top',
  'transform',
  'transform-origin',
  'transition',
  'transition-delay',
  'transition-duration',
  'transition-property',
  'transition-timing-function',
  'translate',
  'user-select',
  'vertical-align',
  'visibility',
  'white-space',
  'width',
  'will-change',
  'word-break',
  'word-spacing',
  'word-wrap',
  'writing-mode',
  'z-index',
];

var CSS_VALUES = {
  'display': [
    'block', 'inline', 'inline-block', 'flex', 'inline-flex',
    'grid', 'inline-grid', 'none', 'contents', 'table',
    'table-cell', 'table-row', 'list-item', 'flow-root',
  ],
  'position': ['static', 'relative', 'absolute', 'fixed', 'sticky'],
  'overflow': ['visible', 'hidden', 'scroll', 'auto', 'clip'],
  'overflow-x': ['visible', 'hidden', 'scroll', 'auto', 'clip'],
  'overflow-y': ['visible', 'hidden', 'scroll', 'auto', 'clip'],
  'visibility': ['visible', 'hidden', 'collapse'],
  'opacity': ['0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '1'],
  'cursor': [
    'auto', 'default', 'pointer', 'crosshair', 'move', 'text',
    'wait', 'help', 'not-allowed', 'none', 'grab', 'grabbing',
    'zoom-in', 'zoom-out', 'col-resize', 'row-resize', 'ns-resize',
    'ew-resize', 'nwse-resize', 'nesw-resize', 'all-scroll',
  ],
  'float': ['left', 'right', 'none', 'inline-start', 'inline-end'],
  'clear': ['none', 'left', 'right', 'both', 'inline-start', 'inline-end'],
  'box-sizing': ['content-box', 'border-box'],
  'resize': ['none', 'both', 'horizontal', 'vertical'],

  // Flexbox
  'flex-direction': ['row', 'row-reverse', 'column', 'column-reverse'],
  'flex-wrap': ['nowrap', 'wrap', 'wrap-reverse'],
  'flex-flow': ['row nowrap', 'row wrap', 'column nowrap', 'column wrap'],
  'justify-content': [
    'flex-start', 'flex-end', 'center', 'space-between',
    'space-around', 'space-evenly', 'start', 'end',
  ],
  'align-items': [
    'stretch', 'flex-start', 'flex-end', 'center',
    'baseline', 'start', 'end',
  ],
  'align-self': [
    'auto', 'stretch', 'flex-start', 'flex-end',
    'center', 'baseline', 'start', 'end',
  ],
  'align-content': [
    'stretch', 'flex-start', 'flex-end', 'center',
    'space-between', 'space-around', 'space-evenly',
  ],
  'justify-items': ['start', 'end', 'center', 'stretch'],
  'justify-self': ['auto', 'start', 'end', 'center', 'stretch'],
  'flex-grow': ['0', '1', '2', '3'],
  'flex-shrink': ['0', '1', '2', '3'],
  'flex-basis': ['auto', '0', '100%', 'max-content', 'min-content', 'fit-content'],
  'order': ['0', '-1', '1', '2', '3'],

  // Grid
  'grid-template-columns': [
    'none', 'auto', 'repeat(2, 1fr)', 'repeat(3, 1fr)',
    'repeat(4, 1fr)', 'repeat(12, 1fr)', '1fr 1fr',
    'auto 1fr', 'minmax(0, 1fr)',
  ],
  'grid-template-rows': [
    'none', 'auto', 'repeat(2, 1fr)', 'repeat(3, 1fr)',
    'minmax(0, 1fr)',
  ],
  'grid-column': ['auto', 'span 1', 'span 2', 'span 3', '1 / -1', '1 / 2', '1 / 3'],
  'grid-row': ['auto', 'span 1', 'span 2', 'span 3', '1 / -1'],
  'grid-area': ['auto'],

  // Spacing
  'gap': ['0', '4px', '8px', '12px', '16px', '20px', '24px', '32px', '40px', '48px'],
  'row-gap': ['0', '4px', '8px', '16px', '24px', '32px'],
  'column-gap': ['0', '4px', '8px', '16px', '24px', '32px'],

  // Sizing
  'width': [
    'auto', '100%', '100vw', 'fit-content', 'max-content', 'min-content',
    '25%', '33.333%', '50%', '66.666%', '75%',
  ],
  'height': [
    'auto', '100%', '100vh', 'fit-content', 'max-content', 'min-content',
  ],
  'min-width': ['0', 'auto', '100%', 'fit-content', 'max-content', 'min-content'],
  'max-width': ['none', '100%', '100vw', 'fit-content', 'max-content', 'min-content'],
  'min-height': ['0', 'auto', '100%', '100vh'],
  'max-height': ['none', '100%', '100vh'],

  // Typography
  'font-size': [
    '10px', '11px', '12px', '13px', '14px', '16px', '18px', '20px',
    '24px', '28px', '32px', '36px', '40px', '48px', '56px', '64px',
    '0.75rem', '0.875rem', '1rem', '1.125rem', '1.25rem', '1.5rem',
    '1.75rem', '2rem', '2.25rem', '2.5rem', '3rem', '4rem',
    'small', 'medium', 'large', 'x-large', 'xx-large', 'smaller', 'larger',
  ],
  'font-weight': ['100', '200', '300', '400', '500', '600', '700', '800', '900', 'normal', 'bold', 'bolder', 'lighter'],
  'font-style': ['normal', 'italic', 'oblique'],
  'font-variant': ['normal', 'small-caps'],
  'font-family': [
    'sans-serif', 'serif', 'monospace', 'system-ui', 'inherit',
    "'Inter', sans-serif", "'Roboto', sans-serif", "'Open Sans', sans-serif",
    "'Helvetica Neue', sans-serif", "'Georgia', serif",
    "'JetBrains Mono', monospace", "'Fira Code', monospace",
  ],
  'line-height': ['1', '1.2', '1.4', '1.5', '1.6', '1.75', '2', 'normal'],
  'letter-spacing': ['normal', '-0.05em', '-0.025em', '0', '0.025em', '0.05em', '0.1em'],
  'word-spacing': ['normal', '0', '1px', '2px', '4px'],
  'text-align': ['left', 'right', 'center', 'justify', 'start', 'end'],
  'text-decoration': ['none', 'underline', 'overline', 'line-through'],
  'text-decoration-line': ['none', 'underline', 'overline', 'line-through'],
  'text-decoration-style': ['solid', 'double', 'dotted', 'dashed', 'wavy'],
  'text-transform': ['none', 'uppercase', 'lowercase', 'capitalize', 'full-width'],
  'text-overflow': ['clip', 'ellipsis'],
  'white-space': ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line', 'break-spaces'],
  'word-break': ['normal', 'break-all', 'keep-all', 'break-word'],
  'word-wrap': ['normal', 'break-word'],
  'writing-mode': ['horizontal-tb', 'vertical-rl', 'vertical-lr'],
  'vertical-align': ['baseline', 'top', 'middle', 'bottom', 'text-top', 'text-bottom', 'sub', 'super'],

  // Colors / Backgrounds
  'color': ['inherit', 'currentColor', 'transparent', '#000', '#fff', '#333', '#666', '#999'],
  'background-color': ['transparent', 'inherit', 'currentColor', '#fff', '#000', '#f5f5f5'],
  'background-image': ['none', 'linear-gradient()', 'radial-gradient()', 'url()'],
  'background-size': ['auto', 'cover', 'contain', '100%', '100% 100%'],
  'background-position': ['center', 'top', 'bottom', 'left', 'right', 'top left', 'top right', 'bottom left', 'bottom right', '50% 50%'],
  'background-repeat': ['repeat', 'no-repeat', 'repeat-x', 'repeat-y', 'round', 'space'],
  'background-attachment': ['scroll', 'fixed', 'local'],
  'background-clip': ['border-box', 'padding-box', 'content-box', 'text'],
  'background-origin': ['border-box', 'padding-box', 'content-box'],

  // Borders
  'border-style': ['none', 'solid', 'dashed', 'dotted', 'double', 'groove', 'ridge', 'inset', 'outset', 'hidden'],
  'border-width': ['0', '1px', '2px', '3px', '4px', 'thin', 'medium', 'thick'],
  'border-color': ['transparent', 'currentColor', 'inherit', '#000', '#ccc', '#ddd', '#eee'],
  'border-radius': ['0', '2px', '4px', '6px', '8px', '12px', '16px', '20px', '24px', '50%', '9999px'],
  'border-collapse': ['collapse', 'separate'],
  'outline': ['none', '0'],
  'outline-style': ['none', 'solid', 'dashed', 'dotted', 'double'],
  'outline-offset': ['0', '2px', '4px', '-2px'],

  // Shadows
  'box-shadow': ['none', '0 1px 3px rgba(0,0,0,0.1)', '0 4px 6px rgba(0,0,0,0.1)', '0 10px 15px rgba(0,0,0,0.1)', '0 20px 25px rgba(0,0,0,0.1)', 'inset 0 1px 3px rgba(0,0,0,0.1)'],
  'text-shadow': ['none', '0 1px 2px rgba(0,0,0,0.5)', '1px 1px 2px rgba(0,0,0,0.3)'],

  // Transform / Transition / Animation
  'transform': ['none', 'translateX()', 'translateY()', 'translate()', 'scale()', 'scaleX()', 'scaleY()', 'rotate()', 'skew()', 'matrix()'],
  'transform-origin': ['center', 'top', 'bottom', 'left', 'right', 'top left', '50% 50%', '0 0'],
  'transition': ['none', 'all 0.2s ease', 'all 0.3s ease', 'opacity 0.2s ease', 'transform 0.2s ease', 'color 0.2s ease', 'background-color 0.2s ease'],
  'transition-duration': ['0s', '0.1s', '0.15s', '0.2s', '0.3s', '0.5s', '1s'],
  'transition-timing-function': ['ease', 'ease-in', 'ease-out', 'ease-in-out', 'linear', 'step-start', 'step-end'],
  'transition-delay': ['0s', '0.1s', '0.2s', '0.3s', '0.5s'],
  'animation-timing-function': ['ease', 'ease-in', 'ease-out', 'ease-in-out', 'linear', 'steps(1)', 'cubic-bezier()'],
  'animation-fill-mode': ['none', 'forwards', 'backwards', 'both'],
  'animation-direction': ['normal', 'reverse', 'alternate', 'alternate-reverse'],
  'animation-play-state': ['running', 'paused'],
  'animation-iteration-count': ['1', '2', '3', 'infinite'],

  // Misc
  'object-fit': ['fill', 'contain', 'cover', 'none', 'scale-down'],
  'object-position': ['center', 'top', 'bottom', 'left', 'right', '50% 50%'],
  'pointer-events': ['auto', 'none', 'all', 'fill', 'stroke', 'painted', 'visible'],
  'user-select': ['auto', 'none', 'text', 'all', 'contain'],
  'appearance': ['none', 'auto'],
  'will-change': ['auto', 'transform', 'opacity', 'scroll-position'],
  'content': ['none', 'normal', '""', "''"],
  'list-style': ['none', 'disc', 'circle', 'square', 'decimal', 'lower-alpha', 'upper-alpha'],
  'list-style-type': ['none', 'disc', 'circle', 'square', 'decimal', 'lower-roman', 'upper-roman', 'lower-alpha', 'upper-alpha'],
  'list-style-position': ['inside', 'outside'],
  'scroll-behavior': ['auto', 'smooth'],
  'filter': ['none', 'blur()', 'brightness()', 'contrast()', 'grayscale()', 'hue-rotate()', 'invert()', 'opacity()', 'saturate()', 'sepia()', 'drop-shadow()'],
  'backdrop-filter': ['none', 'blur()', 'brightness()', 'contrast()', 'grayscale()', 'saturate()'],
  'clip-path': ['none', 'circle()', 'ellipse()', 'polygon()', 'inset()', 'path()'],
  'columns': ['auto', '1', '2', '3', '4'],
  'z-index': ['auto', '0', '1', '10', '100', '999', '1000', '9999', '-1'],
};
